baseURL = "https://agri-ai.nl"
title = "AGRI AI"
author = "Cynthia Zhu"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true


[params]

  showBlog = false
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.png"
    alt = "Tella Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "AGRI AI"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "AGRI AI, delivers AI servies for Argiculture"
    meta_og_title = "AGRI AI"
    meta_og_type = "website"
    meta_og_url = "https://agri-ai.nl"
    meta_og_image = "https://agri-ai.nl/img/slide/slide02.webp"
    meta_og_description = "AGRI AI, delivers AI servies for Argiculture"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "Services"
    name = "Services"
    url = "/services/"
    weight = 1

  [[menu.main]]
    identifier = "Mission"
    name = "Mission"
    url = "/mission/"
    weight = 2

  [[menu.main]]
    identifier = "Vision"
    name = "Vision"
    url = "/vision/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1
